name: Publish

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'
      - '/integration/*'
      - 'package*.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN} > .npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Bootstrap
        run: npm ci

      - name: Lib Tests
        run: npx lerna run test --scope @joist/*

      - name: Integration Tests
        run: npx lerna run test --scope @joist-app/* --concurrency 1

      - name: Build Integrations
        run: npx lerna run build --scope @joist-app/*

      - name: Check Bundle Sizes
        run: npx lerna run size --scope @joist-app/*

      - name: Publish
        run: npx lerna publish --canary --preid canary.$(date +"%s") --yes
